services:
  proxy:
    image: nginx
    volumes:
      - type: bind
        source: ./proxy/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: false
      # Optionally, if Nginx needs to write to the directory:
      # - type: bind
      #   source: ./proxy/nginx_logs
      #   target: /var/log/nginx
    ports:
      - 80:80
    depends_on:
      - backend

  backend:
    build:
      context: backend
      target: dev-envs
    # Optionally, if Docker socket access is necessary:
    # volumes:
    #   - /var/run/docker.sock:/var/run/docker.sock

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
